# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-02 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='updated',
            new_name='created',
        ),
    ]
