# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-02 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_auto_20180402_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='common_title',
        ),
        migrations.AddField(
            model_name='commonname',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='species.Species'),
            preserve_default=False,
        ),
    ]
