# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-02 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0006_auto_20180402_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classname',
            options={'verbose_name': 'Species Class', 'verbose_name_plural': 'Species Classes'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Species Family', 'verbose_name_plural': 'Species Families'},
        ),
        migrations.AlterModelOptions(
            name='genus',
            options={'verbose_name': 'Species Genus', 'verbose_name_plural': 'Genera'},
        ),
        migrations.AlterModelOptions(
            name='kingdom',
            options={'verbose_name': 'Species Kingdom', 'verbose_name_plural': 'Species Kingdoms'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Species Order', 'verbose_name_plural': 'Species Orders'},
        ),
        migrations.AlterModelOptions(
            name='phylum',
            options={'verbose_name': 'Species Phylum', 'verbose_name_plural': 'Species Phyla'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name': 'species', 'verbose_name_plural': 'species'},
        ),
        migrations.AddField(
            model_name='species',
            name='basis_of_record',
            field=models.CharField(choices=[('', '-----------'), ('hob', 'HumanObservation'), ('lis', 'LivingSpeciment'), ('prs', 'PreservedSpecimen'), ('fos', 'FossilSpecimen'), ('mob', 'MachineObservation')], default='hob', help_text='The specific nature of the data record - a subtype of the dcterms:type. ', max_length=3),
        ),
        migrations.AddField(
            model_name='species',
            name='category',
            field=models.IntegerField(choices=[('', '----------'), (10, 'BIRDS'), (20, 'REPTILES'), (30, 'MAMMALS'), (40, 'FRESHWATER FISH'), (50, 'CRUSTACEANS'), (60, 'SHARKS AND RAYS'), (70, 'FLORA')], default=30),
        ),
        migrations.AlterField(
            model_name='classname',
            name='title',
            field=models.CharField(help_text='The full scientific name of the class in which the taxon is classified.', max_length=40),
        ),
        migrations.AlterField(
            model_name='family',
            name='title',
            field=models.CharField(help_text='The full scientific name of the family in which the taxon is classified.', max_length=40),
        ),
        migrations.AlterField(
            model_name='genus',
            name='title',
            field=models.CharField(help_text='The full scientific name of the genus in which the taxon is classified', max_length=40),
        ),
        migrations.AlterField(
            model_name='kingdom',
            name='title',
            field=models.CharField(help_text='The full scientific name of the kingdom in which the taxon is classified. Example: "Animalia", "Plantae"', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(help_text='The full scientific name of the order in which the taxon is classified.', max_length=40),
        ),
        migrations.AlterField(
            model_name='phylum',
            name='title',
            field=models.CharField(help_text='The full scientific name of the phylum or division in which the taxon is classified.', max_length=40),
        ),
        migrations.AlterField(
            model_name='speciename',
            name='title',
            field=models.CharField(help_text='Title of the Kingdom of this species', max_length=40),
        ),
    ]
