# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-02 07:56
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0008_auto_20180402_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='speciename',
            new_name='specie',
        ),
        migrations.AlterField(
            model_name='species',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['genus', 'specie']),
        ),
    ]
