# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-02 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0009_auto_20180402_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='basis_of_record',
            field=models.CharField(choices=[('', '-----------'), ('hob', 'HumanObservation'), ('lis', 'LivingSpeciment'), ('prs', 'PreservedSpecimen'), ('fos', 'FossilSpecimen'), ('mob', 'MachineObservation')], default='hob', help_text='The specific nature of the data record - a subtype of the dcterms:type. ', max_length=3, verbose_name='record basis'),
        ),
        migrations.AlterField(
            model_name='species',
            name='classname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.ClassName', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='species',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.SpecieName', verbose_name='specie'),
        ),
    ]
