# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-02 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0010_auto_20180402_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='species_pics/%Y-%m-%d/', verbose_name='Species Image')),
                ('description', models.TextField(help_text='Any description of the image e.g attribution, location etc.')),
            ],
        ),
        migrations.AlterField(
            model_name='speciename',
            name='title',
            field=models.CharField(help_text='Species name of this species, ex. Familiaris, from Canis Familiaris', max_length=40),
        ),
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.IntegerField(choices=[('', '----------'), (10, 'BIRDS'), (20, 'REPTILES'), (30, 'MAMMALS'), (40, 'FRESHWATER FISH'), (50, 'CRUSTACEANS'), (60, 'SHARKS AND RAYS'), (70, 'FLORA')], default=30, help_text='The category where this species belong to.'),
        ),
        migrations.AlterField(
            model_name='species',
            name='classname',
            field=models.ForeignKey(help_text='The full scientific name of the class in which the taxon is classified.', on_delete=django.db.models.deletion.CASCADE, to='species.ClassName', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='species',
            name='family',
            field=models.ForeignKey(help_text='The full scientific name of the family in which the taxon is classified.', on_delete=django.db.models.deletion.CASCADE, to='species.Family'),
        ),
        migrations.AlterField(
            model_name='species',
            name='genus',
            field=models.ForeignKey(help_text='The full scientific name of the genus in which the taxon is classified', on_delete=django.db.models.deletion.CASCADE, to='species.Genus'),
        ),
        migrations.AlterField(
            model_name='species',
            name='kingdom',
            field=models.ForeignKey(help_text='The full scientific name of the kingdom in which the taxon is classified. Example: "Animalia", "Plantae"', on_delete=django.db.models.deletion.CASCADE, to='species.Kingdom'),
        ),
        migrations.AlterField(
            model_name='species',
            name='order',
            field=models.ForeignKey(help_text='The full scientific name of the order in which the taxon is classified.', on_delete=django.db.models.deletion.CASCADE, to='species.Order'),
        ),
        migrations.AlterField(
            model_name='species',
            name='phylum',
            field=models.ForeignKey(help_text='The full scientific name of the phylum or division in which the taxon is classified.', on_delete=django.db.models.deletion.CASCADE, to='species.Phylum'),
        ),
        migrations.AlterField(
            model_name='species',
            name='specie',
            field=models.ForeignKey(help_text='Species name of this species, ex. Familiaris, from Canis Familiaris.', on_delete=django.db.models.deletion.CASCADE, to='species.SpecieName', verbose_name='species name'),
        ),
        migrations.AddField(
            model_name='speciesimage',
            name='species',
            field=models.ForeignKey(help_text='Add your species image(s) here', on_delete=django.db.models.deletion.CASCADE, to='species.Species'),
        ),
    ]
