# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-02 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0011_auto_20180402_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesimage',
            name='description',
            field=models.TextField(blank=True, help_text='Any description of the image e.g attribution, location etc.'),
        ),
    ]
