# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-02 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0012_auto_20180402_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='specie',
            field=models.CharField(help_text='Species name of this species, ex. Familiaris, from Canis Familiaris.', max_length=80, verbose_name='species name'),
        ),
    ]
