# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-02 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0013_auto_20180402_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='taxonomic_notes',
            field=models.TextField(blank=True, help_text='Any notes you wan to add about this species'),
        ),
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.IntegerField(choices=[('', '----------'), (10, 'BIRDS'), (20, 'REPTILES'), (30, 'MAMMALS'), (40, 'FRESHWATER FISH'), (50, 'CRUSTACEANS'), (60, 'SHARKS AND RAYS'), (70, 'FLORA')], help_text='The category where this species belong to.'),
        ),
    ]
