# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-02 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0015_delete_speciename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='sciname_author',
            field=models.CharField(max_length=80, verbose_name='SciName Author'),
        ),
        migrations.AlterField(
            model_name='species',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['genus', 'specie'], verbose_name='Scientific Name'),
        ),
    ]
