# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0017_auto_20180402_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='category',
        ),
        migrations.AddField(
            model_name='classname',
            name='simple_term',
            field=models.CharField(blank=True, help_text='term used by many to easily identify this species e.g Aves is to birds, ', max_length=80),
        ),
    ]
