# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0018_auto_20180405_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Write which group this animal belongs to, relative to species's class e.g aves for birds", max_length=40)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='classname',
            name='simple_term',
        ),
        migrations.AddField(
            model_name='classname',
            name='group_as',
            field=models.ForeignKey(blank=True, help_text='term used by many to easily identify this species e.g Aves is to birds, ', null=True, on_delete=django.db.models.deletion.CASCADE, to='species.Category'),
        ),
    ]
