# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-05 00:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('species', '0019_auto_20180405_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classname',
            name='group_as',
            field=models.ForeignKey(blank=True, help_text='term used by many to easily identify this species e.g Aves is to birds, ', null=True, on_delete=django.db.models.deletion.CASCADE, to='species.Category', verbose_name='Categorize as'),
        ),
        migrations.AlterField(
            model_name='species',
            name='basis_of_record',
            field=models.CharField(choices=[('', '-----------'), ('hob', 'Human Observation'), ('lis', 'Living Speciment'), ('prs', 'Preserved Specimen'), ('fos', 'Fossil Specimen'), ('mob', 'Machine Observation')], default='hob', help_text='The specific nature of the data record - a subtype of the dcterms:type. ', max_length=3, verbose_name='record basis'),
        ),
        migrations.AlterField(
            model_name='species',
            name='sciname_author',
            field=models.CharField(max_length=80, verbose_name='Scientific name author'),
        ),
        migrations.AlterField(
            model_name='species',
            name='specie',
            field=models.CharField(help_text='Species name of this species, ex. Familiaris, from Canis Familiaris.', max_length=80, verbose_name='Species'),
        ),
    ]
