# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-05 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0022_auto_20180405_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonname',
            name='scientific_name',
        ),
    ]
