# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-11 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0024_auto_20180411_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='specie_profile_pics/%Y-%m-%d/', verbose_name='Species Profile Pic'),
        ),
    ]
