# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-12 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0025_species_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciesimage',
            old_name='image',
            new_name='pic',
        ),
    ]
